version: '3.3'

services:
  db:
    image: 'postgres:latest'
    restart: always
    #volumes:
    #  - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mi_db
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080